name: Step Types

on: workflow_dispatch

jobs:
    say-hello-inline-bash:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"
    
    say-hello-inline-python:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello from an inline python script in a GitHub Action Workflow!"
              shell: python

    say-hello-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/hello-world-action@v1
              with:
                who-to-greet: "Someone I know that GitHub Actions can greet them ðŸ¤–"