name: Third Party Auth
on: workflow_dispatch

jobs:
  auth-to-aws-statics:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials using static credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
        
  
  auth-to-aws-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      
    steps:
      - name: "Configure AWS Credentials using OIDC"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::271071983698:role/github-actions-role